Feature: asciibinder clean

  This command cleans up any files generated by AsciiBinder

  Scenario: A user wants to clean a docs repo of generated content
    Given a valid AsciiBinder docs repo
    And the docs repo contains generated content
    When the user runs `asciibinder clean` on that repo directory
    Then the generated content is removed

  Scenario: A user cleans a docs repo with no generated content
    Given a valid AsciiBinder docs repo
    And the docs repo contains no generated content
    When the user runs `asciibinder clean` on that repo directory
    Then the program exits without errors

  Scenario: A user cleans a directory that is not a docs repo
    Given an invalid AsciiBinder docs repo
    When the user runs `asciibinder clean` on that repo directory
    Then the program exits with a warning
